# Generated by Django 5.2.6 on 2025-11-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_salas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
